ref:
  name: GRCh38_Verily_v1
  species: homo_sapiens
  build: GRCh38
  # Reference genome
  path: "config/reference/GRCh38_Verily_v1.genome.fa"
  # Index file
  idx: "config/reference/GRCh38_Verily_v1.genome.fa.fai"
  # BED file
  bed: "config/reference/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"
  # Chromosomes
  chr: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,'X','Y']

# Extension of fastq files
ext: ".fq.gz"

# Path to GATK executable
gatk_exe: "config/reference/gatk-4.3.0.0/gatk"

# Don't change the sample_file path
sample_file: "config/misc/samples.tsv" 

params:
  bwa:
    threads: 12
  gatk:
    ApplyBQSR:
        - "-OQ true"
        - "-OBI false"
        - "--add-output-sam-program-record true"
        - "--tmp-dir config/TMP"
    ApplyVQSR_INDEL:
        - "-mode INDEL"
        - "-ts-filter-level 99.7"
        - "--create-output-variant-index true"
        - "--tmp-dir config/TMP"
    ApplyVQSR_SNP:
        - "-mode SNP"
        - "-ts-filter-level 99.7"
        - "--create-output-variant-index true"
        - "--tmp-dir config/TMP"
    BaseRecalibrator:
        - "-OQ true"
        - "--known-sites config/reference/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
        - "--known-sites config/reference/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
        - "--known-sites config/reference/Homo_sapiens_assembly38.known_indels.vcf.gz"
        - "--tmp-dir config/TMP"
    CNNScoreVariants:
        - "-tensor-type read_tensor"
        - "-OVI true"
        - "--tmp-dir config/TMP"
    CombineGVCFs:
        - "-OVI true"
        - "--tmp-dir config/TMP"
    FilterVariantTranches:
        - "--resource config/reference/hapmap_3.3.hg38.vcf.gz"
        - "--resource config/reference/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
        - "--info-key CNN_2D"
        - "--snp-tranche 99.95"
        - "--indel-tranche 99.4"
        - "--tmp-dir config/TMP"
    GenomicsDBImport:
        - "--batch-size 20"
        - "--genomicsdb-shared-posixfs-optimizations true"
        - "--bypass-feature-reader true"
        - "--tmp-dir config/TMP"
    GenotypeGVCFs:
        - "-G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation"
        - "--use-new-qual-calculator true"
    HaplotypeCaller:
        - "--pcr-indel-model NONE"
        - "--native-pair-hmm-threads 1"
        - "-G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation"
        - "-ERC GVCF"
        - "--tmp-dir config/TMP"
    VariantRecalibrator_INDEL:
        - "-an QD -an ReadPosRankSum -an FS -an SOR"
        - "-mode INDEL"
        - "--max-gaussians 4"
        - "--tranches-file results/cohort/recalibrate_indel.tranches"
        - "--rscript-file config/misc/plots_indel.R"
        - "--dont-run-rscript"
        - "--resource:mills,known=false,training=true,truth=true,prior=12 config/reference/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
        - "--resource:axiomPoly,known=false,training=true,truth=false,prior=10 config/reference/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
        - "--resource:dbsnp,known=true,training=false,truth=false,prior=2 config/reference/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
        - "--tmp-dir config/TMP"
    VariantRecalibrator_SNP:
        - "-an QD -an ReadPosRankSum -an FS -an SOR"
        - "-mode SNP"
        - "--max-gaussians 6"
        - "--tranches-file results/cohort/recalibrate_snp.tranches"
        - "--rscript-file config/misc/plots_snp.R"
        - "--dont-run-rscript"
        - "--resource:hapmap,known=false,training=true,truth=true,prior=15 config/reference/hapmap_3.3.hg38.vcf.gz"
        - "--resource:omni,known=false,training=true,truth=false,prior=12 config/reference/1000G_omni2.5.hg38.vcf.gz"
        - "--resource:1000G,known=false,training=true,truth=false,prior=10 config/reference/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
        - "--resource:dbsnp,known=true,training=false,truth=false,prior=7 config/reference/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
        - "--tmp-dir config/TMP"
  picard:
    MarkDuplicates: 
        - "--VALIDATION_STRINGENCY SILENT"
        - "--OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500"
        - "--ASSUME_SORT_ORDER coordinate"
        - "--CLEAR_DT false"
        - "--CREATE_INDEX false"
        - "--READ_NAME_REGEX null"
        - "--TMP_DIR config/TMP"
    MergeVcfs:
        - "--TMP_DIR config/TMP"
  vep:
    parameters:
        - "--dir_cache config/reference/v109"
        - "--dir_plugins config/reference/Plugins"
        - "--assembly GRCh38"
        - "--cache_version 109"
        - "--offline"
        - "--merged"
        - "--use_transcript_ref"
        - "--transcript_version"
        - "--format vcf"
        - "--no_stats"
        - "--verbose"
        - "--symbol"
        - "--sift b"
        - "--polyphen b"
        - "--canonical"
        - "--biotype"
        - "--af"
        - "--af_1kg"
        - "--af_gnomade"
        - "--af_gnomadg"
        - "--max_af"
        - "--uniprot"
        - "--mane"
        - "--hgvs"
        - "--hgvsg"
        - "--force"
        - "--fork 4"
    plugins:
        - "--plugin CADD,config/reference/whole_genome_SNVs.tsv.gz,config/reference/gnomad.genomes.r3.0.indel.tsv.gz"
        - "--plugin PrimateAI,config/reference/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.gz"
        - "--plugin REVEL,config/reference/revel-v1.3_all_chromosomes.tsv.gz"
        - "--plugin SpliceAI,snv=config/reference/spliceai_scores.raw.snv.hg38.vcf.gz,indel=config/reference/spliceai_scores.raw.indel.hg38.vcf.gz"
